### ISSUE TITLE
Comment on SIW performance

### ISSUE THREAD

**Issue by assaad** [socialsensor/graphdb-benchmarks#19]
Hello, for the SIW performance of the paper, first I don't see why you did the log of time in ms. 
You could simply put the time in s for each block
Second, the diagrams are not linear in the log scale. they are almost constant, and the time is a bit dropping (and does not mean that the actual execution time should grow exponentially with the graph size). 
After I re-executed your benchmarks, I saw that the time to insert 1000 edge drop a bit the more blocks are inserted, this is due to the fact that the nodes are already created in the graph and/or cached, so the average block insert speed gets a bit faster with time, but according to my observation, it's quite consistent constant speed: in the beginning 1000 edges insert cost 5260 ms, because potentially all the nodes in the 1000 edges need to be created. 
Later on, after a million insert, the 1000 edges insert cost 2222 ms, because potentially all nodes are already cached/created,
Nice benchmark anyway, 
Cheers!

**Comment by sarovios** [comment]
Hi,

> Hello, for the SIW performance of the paper, first I don't see why you did the log of time in ms. 
> You could simply put the time in s for each block

As we note in the paper we used log of time for better representation, i.e. to allow the range of execution time to be displayed without small values being compressed down into bottom of the graph.

> Second, the diagrams are not linear in the log scale. they are almost constant, and the time is a bit dropping (and does not mean that the actual execution time should grow exponentially with the graph size). 

That was the outcome for the CW which is linear and not SIW.

> After I re-executed your benchmarks, I saw that the time to insert 1000 edge drop a bit the more blocks are inserted, this is due to the fact that the nodes are already created in the graph and/or cached, so the average block insert speed gets a bit faster with time, but according to my observation, it's quite consistent constant speed: in the beginning 1000 edges insert cost 5260 ms, because potentially all the nodes in the 1000 edges need to be created. 
> Later on, after a million insert, the 1000 edges insert cost 2222 ms, because potentially all nodes are already cached/created,

That's correct. Also you need to take into account the cold cache effect of each database.

Thanks for your interest.
Cheers.
