### ISSUE TITLE
Issue with compiling project

### ISSUE THREAD

**Issue by AlyonaGavrylei** [socialsensor/graphdb-benchmarks#6]
Dear developers!
I several times tried today to compile project with maven. And every time I got different errors.
The last one was this:

Information:Using javac 1.7.0_79 to compile java sources
Information:java: Errors occurred while compiling module 'graphdb-benchmarks'
Information:Module "graphdb-benchmarks" was fully rebuilt due to project configuration/dependencies changes
Information:01.07.15, 18:00 - Compilation completed with 100 errors and 5 warnings in 3s 485ms
/Users/alyona/Documents/Distiller/graphdb-benchmarks/src/main/java/eu/socialsensor/graphdatabases/OrientGraphDatabase.java
Error:(12, 45) java: cannot find symbol
  symbol:   class OrientEdgeType
  location: package com.tinkerpop.blueprints.impls.orient
Error:(13, 45) java: cannot find symbol
  symbol:   class OrientExtendedGraph
  location: package com.tinkerpop.blueprints.impls.orient
Error:(15, 45) java: cannot find symbol
  symbol:   class OrientGraphFactory
  location: package com.tinkerpop.blueprints.impls.orient
Error:(16, 45) java: cannot find symbol
  symbol:   class OrientGraphNoTx
  location: package com.tinkerpop.blueprints.impls.orient
Error:(18, 45) java: cannot find symbol
  symbol:   class OrientVertexType
  location: package com.tinkerpop.blueprints.impls.orient
Error:(19, 52) java: package com.tinkerpop.blueprints.impls.orient.asynch does not exist
Error:(45, 17) java: cannot find symbol
  symbol:   class OrientExtendedGraph
  location: class eu.socialsensor.graphdatabases.OrientGraphDatabase
Error:(369, 43) java: cannot find symbol
  symbol:   class OrientExtendedGraph
  location: class eu.socialsensor.graphdatabases.OrientGraphDatabase
Error:(395, 17) java: cannot find symbol
  symbol:   class OrientExtendedGraph
  location: class eu.socialsensor.graphdatabases.OrientGraphDatabase
/Users/alyona/Documents/Distiller/graphdb-benchmarks/src/main/java/eu/socialsensor/insert/OrientAbstractInsertion.java
Error:(29, 45) java: cannot find symbol
  symbol:   class OrientExtendedGraph
  location: package com.tinkerpop.blueprints.impls.orient
Error:(30, 52) java: package com.tinkerpop.blueprints.impls.orient.asynch does not exist
Error:(43, 19) java: cannot find symbol
  symbol:   class OrientExtendedGraph
  location: class eu.socialsensor.insert.OrientAbstractInsertion
Error:(48, 40) java: cannot find symbol
  symbol:   class OrientExtendedGraph
  location: class eu.socialsensor.insert.OrientAbstractInsertion
/Users/alyona/Documents/Distiller/graphdb-benchmarks/src/main/java/eu/socialsensor/query/Neo4jQuery.java
Error:(3, 27) java: package org.neo4j.graphalgo does not exist
Error:(4, 27) java: package org.neo4j.graphalgo does not exist
Error:(11, 33) java: package org.neo4j.graphdb.factory does not exist
Error:(12, 24) java: cannot find symbol
  symbol:   class GraphDatabaseAPI
  location: package org.neo4j.kernel
Error:(14, 25) java: package org.neo4j.tooling does not exist
/Users/alyona/Documents/Distiller/graphdb-benchmarks/src/main/java/eu/socialsensor/insert/OrientMassiveInsertion.java
Error:(4, 48) java: package com.orientechnologies.orient.graph.batch does not exist
Error:(5, 45) java: cannot find symbol
  symbol:   class OrientGraphNoTx
  location: package com.tinkerpop.blueprints.impls.orient
/Users/alyona/Documents/Distiller/graphdb-benchmarks/src/main/java/eu/socialsensor/clustering/Cache.java
Error:(7, 31) java: package com.google.common.cache does not exist
Error:(8, 31) java: package com.google.common.cache does not exist
Error:(9, 31) java: package com.google.common.cache does not exist
Error:(22, 9) java: cannot find symbol
  symbol:   class LoadingCache
  location: class eu.socialsensor.clustering.Cache
Error:(23, 9) java: cannot find symbol
  symbol:   class LoadingCache
  location: class eu.socialsensor.clustering.Cache
Error:(24, 9) java: cannot find symbol
  symbol:   class LoadingCache
  location: class eu.socialsensor.clustering.Cache
Error:(25, 9) java: cannot find symbol
  symbol:   class LoadingCache
  location: class eu.socialsensor.clustering.Cache
Error:(26, 9) java: cannot find symbol
  symbol:   class LoadingCache
  location: class eu.socialsensor.clustering.Cache
/Users/alyona/Documents/Distiller/graphdb-benchmarks/src/main/java/eu/socialsensor/graphdatabases/Neo4jGraphDatabase.java
Error:(11, 25) java: cannot find symbol
  symbol:   class DynamicLabel
  location: package org.neo4j.graphdb
Error:(13, 25) java: cannot find symbol
  symbol:   class Label
  location: package org.neo4j.graphdb
Error:(17, 25) java: cannot find symbol
  symbol:   class ResourceIterable
  location: package org.neo4j.graphdb
Error:(19, 33) java: package org.neo4j.graphdb.factory does not exist
Error:(20, 32) java: package org.neo4j.graphdb.schema does not exist
Error:(21, 32) java: package org.neo4j.graphdb.schema does not exist
Error:(23, 24) java: cannot find symbol
  symbol:   class GraphDatabaseAPI
  location: package org.neo4j.kernel
Error:(24, 25) java: package org.neo4j.tooling does not exist
Error:(25, 36) java: package org.neo4j.unsafe.batchinsert does not exist
Error:(26, 36) java: package org.neo4j.unsafe.batchinsert does not exist
Error:(47, 9) java: cannot find symbol
  symbol:   class Schema
  location: class eu.socialsensor.graphdatabases.Neo4jGraphDatabase
Error:(48, 9) java: cannot find symbol
  symbol:   class IndexDefinition
  location: class eu.socialsensor.graphdatabases.Neo4jGraphDatabase
Error:(50, 17) java: cannot find symbol
  symbol:   class BatchInserter
  location: class eu.socialsensor.graphdatabases.Neo4jGraphDatabase
Error:(56, 23) java: cannot find symbol
  symbol:   class Label
  location: class eu.socialsensor.graphdatabases.Neo4jGraphDatabase
/Users/alyona/Documents/Distiller/graphdb-benchmarks/src/main/java/eu/socialsensor/graphdatabases/TitanGraphDatabase.java
Error:(15, 36) java: package com.thinkaurelius.titan.core does not exist
Error:(16, 36) java: package com.thinkaurelius.titan.core does not exist
Error:(17, 36) java: package com.thinkaurelius.titan.core does not exist
Error:(18, 43) java: package com.thinkaurelius.titan.core.schema does not exist
Error:(19, 41) java: package com.thinkaurelius.titan.core.util does not exist
Error:(25, 34) java: package com.tinkerpop.gremlin.java does not exist
Error:(48, 16) java: cannot find symbol
  symbol:   class TitanGraph
  location: class eu.socialsensor.graphdatabases.TitanGraphDatabase
Error:(49, 27) java: cannot find symbol
  symbol:   class TitanGraph
  location: class eu.socialsensor.graphdatabases.TitanGraphDatabase
/Users/alyona/Documents/Distiller/graphdb-benchmarks/src/main/java/eu/socialsensor/insert/OrientSingleInsertion.java
Error:(5, 45) java: cannot find symbol
  symbol:   class OrientExtendedGraph
  location: package com.tinkerpop.blueprints.impls.orient
Error:(27, 32) java: cannot find symbol
  symbol:   class OrientExtendedGraph
  location: class eu.socialsensor.insert.OrientSingleInsertion
/Users/alyona/Documents/Distiller/graphdb-benchmarks/src/main/java/eu/socialsensor/query/TitanQuery.java
Error:(8, 36) java: package com.thinkaurelius.titan.core does not exist
Error:(9, 36) java: package com.thinkaurelius.titan.core does not exist
Error:(10, 36) java: package com.thinkaurelius.titan.core does not exist
Error:(14, 34) java: package com.tinkerpop.gremlin.java does not exist
Error:(15, 27) java: package com.tinkerpop.pipes does not exist
Error:(16, 43) java: package com.tinkerpop.pipes.branch.LoopPipe does not exist
Error:(30, 17) java: cannot find symbol
  symbol:   class TitanGraph
  location: class eu.socialsensor.query.TitanQuery
Error:(42, 27) java: cannot find symbol
  symbol:   class TitanGraph
  location: class eu.socialsensor.query.TitanQuery
/Users/alyona/Documents/Distiller/graphdb-benchmarks/src/main/java/eu/socialsensor/query/SparkseeQuery.java
Error:(3, 40) java: package com.sparsity.sparksee.algorithms does not exist
Error:(4, 33) java: package com.sparsity.sparksee.gdb does not exist
Error:(5, 33) java: package com.sparsity.sparksee.gdb does not exist
Error:(6, 33) java: package com.sparsity.sparksee.gdb does not exist
Error:(7, 33) java: package com.sparsity.sparksee.gdb does not exist
Error:(8, 33) java: package com.sparsity.sparksee.gdb does not exist
Error:(9, 33) java: package com.sparsity.sparksee.gdb does not exist
Error:(10, 33) java: package com.sparsity.sparksee.gdb does not exist
Error:(22, 17) java: cannot find symbol
  symbol:   class Session
  location: class eu.socialsensor.query.SparkseeQuery
Error:(23, 17) java: cannot find symbol
  symbol:   class Graph
  location: class eu.socialsensor.query.SparkseeQuery
Error:(25, 30) java: cannot find symbol
  symbol:   class Session
  location: class eu.socialsensor.query.SparkseeQuery
/Users/alyona/Documents/Distiller/graphdb-benchmarks/src/main/java/eu/socialsensor/insert/TitanSingleInsertion.java
Error:(13, 36) java: package com.thinkaurelius.titan.core does not exist
Error:(37, 17) java: cannot find symbol
  symbol:   class TitanGraph
  location: class eu.socialsensor.insert.TitanSingleInsertion
Error:(50, 37) java: cannot find symbol
  symbol:   class TitanGraph
  location: class eu.socialsensor.insert.TitanSingleInsertion
/Users/alyona/Documents/Distiller/graphdb-benchmarks/src/main/java/eu/socialsensor/query/OrientQuery.java
Error:(7, 56) java: package com.orientechnologies.orient.graph.sql.functions does not exist
Error:(10, 45) java: cannot find symbol
  symbol:   class OrientExtendedGraph
  location: package com.tinkerpop.blueprints.impls.orient
Error:(21, 11) java: cannot find symbol
  symbol:   class OrientExtendedGraph
  location: class eu.socialsensor.query.OrientQuery
Error:(23, 22) java: cannot find symbol
  symbol:   class OrientExtendedGraph
  location: class eu.socialsensor.query.OrientQuery
/Users/alyona/Documents/Distiller/graphdb-benchmarks/src/main/java/eu/socialsensor/insert/Neo4jSingleInsertion.java
Error:(14, 35) java: package org.neo4j.cypher.javacompat does not exist
Error:(17, 25) java: cannot find symbol
  symbol:   class ResourceIterator
  location: package org.neo4j.graphdb
Error:(19, 24) java: cannot find symbol
  symbol:   class GraphDatabaseAPI
  location: package org.neo4j.kernel
Error:(40, 9) java: cannot find symbol
  symbol:   class ExecutionEngine
  location: class eu.socialsensor.insert.Neo4jSingleInsertion
/Users/alyona/Documents/Distiller/graphdb-benchmarks/src/main/java/eu/socialsensor/graphdatabases/SparkseeGraphDatabase.java
Error:(12, 33) java: package com.sparsity.sparksee.gdb does not exist
Error:(13, 33) java: package com.sparsity.sparksee.gdb does not exist
Error:(14, 33) java: package com.sparsity.sparksee.gdb does not exist
Error:(15, 33) java: package com.sparsity.sparksee.gdb does not exist
Error:(16, 33) java: package com.sparsity.sparksee.gdb does not exist
Error:(17, 33) java: package com.sparsity.sparksee.gdb does not exist
Error:(18, 33) java: package com.sparsity.sparksee.gdb does not exist
Error:(19, 33) java: package com.sparsity.sparksee.gdb does not exist
Error:(20, 33) java: package com.sparsity.sparksee.gdb does not exist
Error:(21, 33) java: package com.sparsity.sparksee.gdb does not exist
Error:(22, 33) java: package com.sparsity.sparksee.gdb does not exist
Error:(23, 33) java: package com.sparsity.sparksee.gdb does not exist
Error:(49, 9) java: cannot find symbol
  symbol:   class SparkseeConfig
  location: class eu.socialsensor.graphdatabases.SparkseeGraphDatabase
Error:(50, 9) java: cannot find symbol
  symbol:   class Sparksee
  location: class eu.socialsensor.graphdatabases.SparkseeGraphDatabase
Error:(51, 9) java: cannot find symbol
  symbol:   class Database
  location: class eu.socialsensor.graphdatabases.SparkseeGraphDatabase
Error:(52, 9) java: cannot find symbol
  symbol:   class Session
  location: class eu.socialsensor.graphdatabases.SparkseeGraphDatabase
Error:(53, 9) java: cannot find symbol
  symbol:   class Graph
  location: class eu.socialsensor.graphdatabases.SparkseeGraphDatabase
Error:(63, 9) java: cannot find symbol
  symbol:   class Value
  location: class eu.socialsensor.graphdatabases.SparkseeGraphDatabase
/Users/alyona/Documents/Distiller/graphdb-benchmarks/src/main/java/eu/socialsensor/benchmarks/FindNeighboursOfAllNodesBenchmark.java
Warning:(53, 66) java: non-varargs call of varargs method with inexact argument type for last parameter;
  cast to java.lang.Object for a varargs call
  cast to java.lang.Object[] for a non-varargs call and to suppress this warning
/Users/alyona/Documents/Distiller/graphdb-benchmarks/src/main/java/eu/socialsensor/benchmarks/SingleInsertionBenchmark.java
Warning:(62, 66) java: non-varargs call of varargs method with inexact argument type for last parameter;
  cast to java.lang.Object for a varargs call
  cast to java.lang.Object[] for a non-varargs call and to suppress this warning
/Users/alyona/Documents/Distiller/graphdb-benchmarks/src/main/java/eu/socialsensor/benchmarks/FindShortestPathBenchmark.java
Warning:(61, 66) java: non-varargs call of varargs method with inexact argument type for last parameter;
  cast to java.lang.Object for a varargs call
  cast to java.lang.Object[] for a non-varargs call and to suppress this warning
/Users/alyona/Documents/Distiller/graphdb-benchmarks/src/main/java/eu/socialsensor/benchmarks/MassiveInsertionBenchmark.java
Warning:(60, 66) java: non-varargs call of varargs method with inexact argument type for last parameter;
  cast to java.lang.Object for a varargs call
  cast to java.lang.Object[] for a non-varargs call and to suppress this warning
/Users/alyona/Documents/Distiller/graphdb-benchmarks/src/main/java/eu/socialsensor/benchmarks/FindNodesOfAllEdgesBenchmark.java
Warning:(54, 66) java: non-varargs call of varargs method with inexact argument type for last parameter;
  cast to java.lang.Object for a varargs call
  cast to java.lang.Object[] for a non-varargs call and to suppress this warning

_______________________

[WARNING] COMPILATION WARNING :
[INFO] -------------------------------------------------------------
[WARNING] /home/alyona/benchmarks/src/main/java/eu/socialsensor/graphdatabases/Neo4jGraphDatabase.java: Some input files use or override a deprecated API.
[WARNING] /home/alyona/benchmarks/src/main/java/eu/socialsensor/graphdatabases/Neo4jGraphDatabase.java: Recompile with -Xlint:deprecation for details.
[WARNING] /home/alyona/benchmarks/src/main/java/eu/socialsensor/query/OrientQuery.java: /home/alyona/benchmarks/src/main/java/eu/socialsensor/query/OrientQuery.java uses unchecked or unsafe operations.
[WARNING] /home/alyona/benchmarks/src/main/java/eu/socialsensor/query/OrientQuery.java: Recompile with -Xlint:unchecked for details.
[INFO] 4 warnings
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/alyona/benchmarks/src/main/java/eu/socialsensor/insert/OrientMassiveInsertion.java:[4,48] cannot find symbol
  symbol:   class OGraphBatchInsertSimple
  location: package com.orientechnologies.orient.graph.batch
[ERROR] /home/alyona/benchmarks/src/main/java/eu/socialsensor/insert/OrientMassiveInsertion.java:[4,48] cannot find symbol
  symbol:   class OGraphBatchInsertSimple
  location: package com.orientechnologies.orient.graph.batch
[ERROR] /home/alyona/benchmarks/src/main/java/eu/socialsensor/insert/OrientMassiveInsertion.java:[42,11] cannot find symbol
  symbol:   class OGraphBatchInsertSimple
  location: class eu.socialsensor.insert.OrientMassiveInsertion
[ERROR] /home/alyona/benchmarks/src/main/java/eu/socialsensor/insert/OrientMassiveInsertion.java:[42,43] cannot find symbol
  symbol:   class OGraphBatchInsertSimple
  location: class eu.socialsensor.insert.OrientMassiveInsertion
[INFO] 4 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.915s
[INFO] Finished at: Wed Jul 01 16:13:27 CST 2015
[INFO] Final Memory: 26M/72M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project graphdb-benchmarks: Compilation failure: Compilation failure:
[ERROR] /home/alyona/benchmarks/src/main/java/eu/socialsensor/insert/OrientMassiveInsertion.java:[4,48] cannot find symbol
[ERROR] symbol:   class OGraphBatchInsertSimple
[ERROR] location: package com.orientechnologies.orient.graph.batch
[ERROR] /home/alyona/benchmarks/src/main/java/eu/socialsensor/insert/OrientMassiveInsertion.java:[4,48] cannot find symbol
[ERROR] symbol:   class OGraphBatchInsertSimple
[ERROR] location: package com.orientechnologies.orient.graph.batch
[ERROR] /home/alyona/benchmarks/src/main/java/eu/socialsensor/insert/OrientMassiveInsertion.java:[42,11] cannot find symbol
[ERROR] symbol:   class OGraphBatchInsertSimple
[ERROR] location: class eu.socialsensor.insert.OrientMassiveInsertion
[ERROR] /home/alyona/benchmarks/src/main/java/eu/socialsensor/insert/OrientMassiveInsertion.java:[42,43] cannot find symbol
[ERROR] symbol:   class OGraphBatchInsertSimple
[ERROR] location: class eu.socialsensor.insert.OrientMassiveInsertion
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Could you help me to find out how to make it works. 
Thanks!

**Comment by sarovios** [comment]
Please see: https://github.com/socialsensor/graphdb-benchmarks/issues/5

Cheers
