### ISSUE TITLE
Mismatch in naming convention between the input.properties and the java code

### ISSUE THREAD

**Issue by ghrab** [socialsensor/graphdb-benchmarks#7]
The parameters in the input.properties config file do not match the ones required to run the code.
E.g., the class GraphDatabaseBenchmark requires a property called "DATASET", while in the properties file it is called "REAL_DATASET".
The class ClusteringBenchmark requires some parameters such as "NODES_CNT", "CACHE_VALUES_CNT" and "CACHE_INCREMENT_FACTOR" which are not present in the file.

**Comment by sarovios** [comment]
This is fixed
